config/routes.rb
Recycle::Application.routes.draw do
  root :to => "regions#index"
  match '/about', :to => 'about#index', :as => 'about'
  match '/waste', :to => 'waste#index', :as => 'waste'
  match '/land/:land_type', :to => 'land_uses#land_type', :as => 'land_type'
  match '/land(/:action)', :to => 'land_uses', :as => 'land'

  resources :regions, :only => [:index, :show]
  resources :councils, :only => [:index, :show]

end

app/models/council.rb
class Council < ActiveRecord::Base
  belongs_to :region

  def council_type_enum
    ['unitary', 'regional', 'territorial']
    # should return any collection accepted by `FormOptionsHelper#options_for_select`
    # See http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-options_for_select
  end
end

app/models/land.rb
class Land < ActiveRecord::Base
  belongs_to :region
  before_validation :fill_in_land_type
  validates :land_type, :presence => true

  YEARS = ['1990', '2008']

  scope :forest, where(:land_type => 'natural forest')
  scope :largest, order('hectares desc')


  def square_kms
    @square_kms ||= hectares.to_f / 100
  end

  def per_region_area
    square_kms / region.area if region.area
  end

  def self.year_json(year)
    where(:year => year).all.inject(Hash.new){|hash, t| hash[t.region.name] = t.per_region_area; hash}.to_json
  end

  protected
  def fill_in_land_type
    self.land_type ||= land_use_class
  end

  def land_use_class
    case official_land_type
    when 'Cropland - Annual'
      'annual cropland'
    when 'Cropland - Perennial'
      'perennial cropland'
    when 'Grassland - High producing'
      'non-native grassland'
    when 'Grassland - Low producing'
      'tussock or bare grassland'
    when 'Grassland - With woody biomass'
      'woody grassland'
    when 'Natural Forest'
      'natural forest'
    when 'Other'
      'other'
    when 'Planted Forest - Pre-1990'
      'pre-1990 planted forest'
    when 'Post 1989 Forest'
      'new forest'
    when 'Settlements'
      'towns and cities'
    when 'Wetland - Open water'
      'water'
    when 'Wetland - Vegetated non forest'
      'wetlands'
    end
  end
end

app/models/landfill.rb
class Landfill < ActiveRecord::Base
end

app/models/population.rb
class Population < ActiveRecord::Base
  belongs_to :region

  YEARS = ['1991', '1996', '2001', '2006', '2010']
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :tonnages
  has_many :populations
  has_many :councils
  has_many :lands

  scope :showable, where('area is not null')   # I'm using area as a proxy to determine whether to show, hack FIXME

  def showable?
    area.present?
  end
end

app/models/tonnage.rb
class Tonnage < ActiveRecord::Base
  belongs_to :region

  YEARS = ['1998', '2001/02', '2010']

  def per_capita
    return nil unless tonnes

    pop = region.populations.where(:year => year_range).first || region.populations.where('year < ?', year.to_i.to_s).first
    if pop
      tonnes / pop.number.to_f
    end
  end

  def self.year_json(year)
    where(:year => year).all.inject(Hash.new){|hash, t| hash[t.region.name] = t.tonnes; hash}.to_json
  end

  def to_polymaps_json
    {region.name => tonnes}.to_json
  end

  protected
  def year_range
    # case year
    # when '1998'
    #   '1996'..'2000'.to_a
    # when '2001/02'
    #   '1999'..'2003'.to_a
    # when '2010'
    #   '2008'..'2012'.to_a
    # end
    single_year = year.to_i
    (single_year-2..single_year+2).to_a.map(&:to_s)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/councils_controller.rb
class CouncilsController < ApplicationController
  respond_to :html, :json

  def index
    respond_with(@councils = Council.all)
  end

  def show
    respond_with(@council = Council.find(params[:id]))
  end

end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  def index
    @region_tonnage = Tonnage.order(:year).all(:include => :region).group_by(&:region)
  end

end

app/controllers/land_uses_controller.rb
class LandUsesController < ApplicationController
  def index
    @lands = Land.order('region_id, land_type, year').all(:include => :region).group_by{|l| [l.region_id, l.land_type]}.map do |key, pair|
      pair.size == 2 ? pair : [nil, pair].flatten
    end
  end

  def land_type
    @land_type = (params[:land_type] || 'Natural forest').humanize
    @short_type = @land_type.split(/\s/).last
    render(:text => 'Land type not found', :status => :not_found) and return if Land.where('land_type = ?', @land_type.downcase).count == 0
    @region_lands = Land.where('land_type = ?', @land_type.downcase).order(:year).all(:include => :region).group_by(&:region)
  end

  def changes_map
    @regions = Region.showable.all
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def index
    @regions = Region.showable.all
  end

  def show
    @region = Region.find(params[:id], :include => [:tonnages, :populations])
    @regional_council = @region.councils.where(:council_type => ['unitary', 'regional']).first

    @forests = @region.lands.forest.order('year').all
    @lands = @region.lands.where(:year => '2008').largest.all
    @tonnage = @region.tonnages.last
  end
end

app/controllers/waste_controller.rb
class WasteController < ApplicationController
  def index
    @region_tonnage = Tonnage.order(:year).all(:include => :region).group_by(&:region)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_region_link(region)
    link_to_if region.showable?, region.name, region_path(region)
  end

  def rubbish_phrase(density)
    if density > 100
      'If we pack in the rubbish in'
    elsif density > 20
      'If landfill rubbish was placed equally across'
    else
      'If we spread landfill rubbish equally across'
    end
  end

  def kg_per_meter(tonnes, sq_kms)
    (tonnes * 1000)/ (sq_kms * 1000000)
  end

  def land_use_class(land)
    case land.land_type
    when 'annual cropland'
      'croplands'
    when 'perennial cropland'
      'croplands'
    when 'non-native grassland'
      'grasslands'
    when 'tussock or bare grassland'
      'grasslands'
    when 'woody grassland'
      'grasslands'
    when 'natural forest'
      'forests'
    when 'other'
      'other'
    when 'pre-1990 planted Forest'
      'forests'
    when 'new forest'
      'forests'
    when 'towns and cities'
      'settlements'
    when 'water'
      'wetlands'
    when 'wetlands'
      'wetlands'
    end
  end
end

app/helpers/councils_helper.rb
module CouncilsHelper
end

app/helpers/land_uses_helper.rb
module LandUsesHelper
end

app/views/about/index.html.erb
<h1>Land and Waste New Zealand</h1>

<a name="about"></a>
<h2>About</h2>

<p>
Are we disposing of more rubbish yearly? Are there still native forests in NZ? What about new forests? Explore these questions and more in this mashup.
</p>

<p>
This mashup attempts to show land and waste data as it changes, and hopefully illuminates any improvements of our environmental impact as well as regressions.
</p>

<p>This website was created by <a href="http://kuahyeow.com">Thong Kuah</a> as a <a href="http://www.mixandmash.org.nz">Mix and Mash NZ competition</a> entry.</p>



<a name="sources"></a>
<h2>Sources</h2>
  <p>
  Land Use Map data 1990 and 2008. <a href="http://creativecommons.org/licenses/by/3.0/nz/">Creative Commons Attribution 3.0 New Zealand</a> Ministry for the Environment (retrieved Sep 2011).
  </p>
    <ul>
      <li>
      New Zealand Land Use Map 1990-2008 (LUM v003)
      http://koordinates.com/#/layer/1414
      </li>
    </ul>
  <p>
  Waste and landfill data - 1998, 2001, 2010. Non-commercial reuse allowed, <a href="http://www.mfe.govt.nz/website/copyright.html">Crown copyright</a> Ministry for the Environment (retrieved Sep 2011).
  </p>
    <ul>
      <li>
      Table 2 - Actual/Estimated regional quantities of waste to waste disposal sites (July 2010)
      http://www.mfe.govt.nz/publications/waste/waste-facilities-survey/page3.html
      </li>
      <li>
      Table 1: Annual waste to landfill by region (2002)
      http://www.mfe.govt.nz/publications/waste/recycling-cost-benefit-analysis-apr07/html/page4.html
      </li>
      <li>
      Waste tonnage by region - Appendix 6, question 44
      http://www.mfe.govt.nz/publications/waste/nat-landfill-census-report-98.pdf
      </li>
    </ul>
  <p>
  Population data from <a href="http://www.stats.govt.nz/about_us/about-this-site/copyright-terms-of-use.aspx">Statistics New Zealand</a> (retrieved Sep 2011). Reuse allowed under the <a href="http://creativecommons.org/licenses/by/3.0/nz/">Creative Commons Attribution 3.0 New Zealand</a>
  </p>
    <ul>
      <li>
      2010 Population Estimate by region
      http://www.stats.govt.nz/browse_for_stats/population/estimates_and_projections/SubnationalPopulationEstimates_HOTP30Jun10.aspx
      </li>
      <li>
      2006 Census by region
      http://www.stats.govt.nz/Census/about-2006-census/regional-summary-tables.aspx
      </li>
      <li>
      2001 Census by region
      http://www.stats.govt.nz/Census/2001-census-data/2001-census-regional-summary.aspx
      </li>
      <li>
      1996 Census by region
      http://www2.stats.govt.nz/domino/external/pasfull/pasfull.nsf/7cf46ae26dcb6800cc256a62000a2248/4c2567ef00247c6acc256aff00093177?OpenDocument
      </li>
    </ul>

app/views/councils/index.html.erb
<h1>Councils#index</h1>
<p>Find me in app/views/councils/index.html.erb</p>

app/views/councils/show.html.erb
<h1><%= @council.name %></h1>
<p>Website: <%= link_to @council.website %></p>

app/views/information/index.html.erb
<h1>Where does your Rubbish go?</h1>

<h3>Landfill tonnage by region and year</h3>
<div class="row">
  <div class="span8 columns">
    <div id="map" style="height: 600px;"></div>
  </div>
  <div class="span8 columns">
    <p>
      This table shows the amount of waste sent to landfills within that region for the given year.
      <em>italic</em> figures denote estimates
    </p>
    <table class="zebra-striped">
      <thead>
      <tr>
        <th>Region</th>
        <th class="numeric">1998 (Tonnes)</th>
        <th class="numeric">2001/02 (Tonnes)</th>
        <th class="numeric">2010 (Tonnes)</th>
      </tr>
      </thead>
      <tbody>
      <% @region_tonnage.each do |region, tonnages| %>
        <tr>
          <% expected = ['1998', '2001/02', '2010'] %>
          <td class="name_and_sparkline">
            <div class="region_short_name" title="<%= region.name %>"><%= region.name %></div>
            <div id="<%= dom_id(region, 'graph') %>" class="aGraph"></div>
          </td>
          <% tonnages.each do |tonnage| %>
            <% while (expects = expected.shift) && (expects != tonnage.year) %>
              <td class="numeric">-</td>
            <% end %>
            <td class="numeric <%= 'estimate' if tonnage.estimate %>"> <%= number_with_delimiter(tonnage.tonnes) || '-' %> <%#= "(#{tonnage.year})" %></td>
          <% end %>
          <% expected.each do %>
            <%= content_tag(:td, '-', :class => 'numeric') %>
          <% end %>
          <% if tonnages.size == 3 %>
            <script>
              drawSparkLine("<%= dom_id(region, 'graph') %>", <%= tonnages.map(&:tonnes).to_json %>);
            </script>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<h3>Annual Landfill tonnage per person</h3>
<p>This table shows the amount of waste per capita sent to landfills within that region for the given year</p>
<table class="zebra-striped">
  <thead>
  <tr>
    <th>Region</th>
    <th class="numeric">1998 (kg)</th>
    <th class="numeric">2001/02 (kg)</th>
    <th class="numeric">2010 (kg)</th>
  </tr>
  </thead>
  <tbody>
  <% @region_tonnage.each do |region, tonnages| %>
    <tr>
      <% expected = ['1998', '2001/02', '2010'] %>
      <td class="name_and_sparkline">
        <div class="region_short_name" title="<%= region.name %>"><%= region.name %></div>
        <div id="<%= dom_id(region, 'graph_per') %>" class="aGraph"></div>
      </td>
      <% tonnages.each do |tonnage| %>
        <% while (expects = expected.shift) && (expects != tonnage.year) %>
          <td class="numeric">-</td>
        <% end %>
        <td class="numeric <%= 'estimate' if tonnage.estimate %>">
          <%= number_with_precision(tonnage.per_capita.try(:*, 1000), :precision => 2) || '-' %></td>
      <% end %>
      <% expected.each do %>
        <%= content_tag(:td, '-', :class => 'numeric') %>
      <% end %>
      <% if tonnages.size == 3 %>
        <script>
          drawSparkLine("<%= dom_id(region, 'graph_per') %>", <%= tonnages.map(&:per_capita).to_json %>);
        </script>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<%= javascript_tag do %>
  var tonnage = <%= raw Tonnage.year_json('2010') %>;

  var tonnes = {}
  for (var t in tonnage) {
    tonnes[regc[t]] = tonnage[t];
  }
<% end %>
<%= javascript_include_tag 'statehood.js' %>

app/views/land_uses/forest.html.erb
<h1>How much <%= @land_type.downcase %> is there?</h1>

<h3><%= @land_type %> area by region and year</h3>
<div class="row">
  <div class="span8 columns">
    <p>2010 <%= @land_type %> area by region. The darker an area is, the higher the proportion of <%= @short_type %> area in that region.
    </p>
    <div id="map" style="height: 600px;"></div>
  </div>
  <div class="span8 columns">
    <p>This table shows the proportion of <%= @short_type %> area compared to the  total region area for the given year.
    </p>
    <table class="zebra-striped">
      <thead>
      <tr>
        <th>Region</th>
        <th class="numeric">1998 (%)</th>
        <th class="numeric">2001/02 (%)</th>
      </tr>
      </thead>
      <tbody>
      <% @region_lands.each do |region, lands| %>
        <tr>
          <% expected = Land::YEARS.dup %>
          <td class="name_and_sparkline">
            <div class="region_short_name" title="<%= region.name %>"><%= show_region_link region %></div>
            <div id="<%= dom_id(region, 'graph_per') %>" class="aGraph"></div>
          </td>
          <% lands.each do |land| %>
            <% while (expects = expected.shift) && (expects != land.year) %>
              <td class="numeric">-</td>
            <% end %>
            <td class="numeric <%= 'estimate' if land.respond_to?(:estimate) && land.estimate %>">
              <%= number_with_precision(land.per_region_area.try(:*, 100), :precision => 2) || '-' %></td>
          <% end %>
          <% expected.each do %>
            <%= content_tag(:td, '-', :class => 'numeric') %>
          <% end %>
          <% if lands.size == Land::YEARS.size %>
            <script>
              drawSparkLine("<%= dom_id(region, 'graph_per') %>", <%= lands.map(&:per_region_area).map(&:to_f).to_json %>);
            </script>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>

  </div>
</div>

<h3><%= @land_type %> area</h3>
<p>
  This table shows the area of <%= @land_type %> within that region for the given year.
</p>
<table class="zebra-striped">
  <thead>
  <tr>
    <th>Region</th>
    <th class="numeric">1990 (sq kms)</th>
    <th class="numeric">2008 (sq kms)</th>
  </tr>
  </thead>
  <tbody>
  <% @region_lands.each do |region, lands| %>
    <tr>
      <% expected = Land::YEARS.dup %>
      <td class="name_and_sparkline">
        <div class="region_short_name" title="<%= region.name %>"><%= show_region_link region %></div>
        <div id="<%= dom_id(region, 'graph') %>" class="aGraph"></div>
      </td>
      <% lands.each do |land| %>
        <% while (expects = expected.shift) && (expects != land.year) %>
          <td class="numeric">-</td>
        <% end %>
        <td class="numeric <%= 'estimate' if land.respond_to?(:estimate) && land.estimate %>"> <%= number_with_precision(land.square_kms, :delimiter => ',', :precision => 2) || '-' %> 
      <% end %>
      <% expected.each do %>
        <%= content_tag(:td, '-', :class => 'numeric') %>
      <% end %>
      <% if lands.size == Land::YEARS.size %>
        <script>
          drawSparkLine("<%= dom_id(region, 'graph') %>", <%= lands.map(&:square_kms).map(&:to_f).to_json %>);
        </script>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>



<%= javascript_tag do %>
  var tonnage = <%= raw Land.where('land_type = ?', @land_type.downcase).year_json('2008') %>;

  var tonnes = {}
  for (var t in tonnage) {
    tonnes[regc[t]] = tonnage[t];
  }
  var preferredColor = "YlGn";
<% end %>
<%= javascript_include_tag 'statehood.js' %>

app/views/land_uses/index.html.erb
<%= content_for :head do %>
  <%= javascript_include_tag 'deadsea.js' %>
  <%= javascript_include_tag 'modestmaps.min.js' %>
  <%= javascript_include_tag 'wax.mm.min.js' %>
<% end %>

<h1>How much of NZ is native forest?</h1>

<div id='ts-embed-1316073824233-script'>
  <%= javascript_include_tag 'ts-land-use' %>
</div>

<p class="alert-message info">Hover over the changed areas (outlined in black) for more information</p>

<h3>Land use types by region and year</h3>
<p>
  This table shows the land area for each land use type in each region. It shows the changes from 1990 to 2008.
</p>

<p>
  <%= label_tag :land_type, :style => 'width: auto;' do %>
    Show only:&nbsp;
  <% end %>
  <%= select_tag :land_type, options_for_select(['All', 'Croplands', 'Forests', 'Grasslands', 'Other', 'Settlements', 'Wetlands'], :include_blank => 'All') %>
</p>

<table id="land_use" class="zebra-striped">
  <thead>
  <tr>
    <th>Region</th>
    <th class="numeric">1990 (hectares)</th>
    <th class="numeric">2008 (hectares)</th>
    <th class="numeric">Difference</th>
  </tr>
  </thead>
  <tbody>
  <% @lands.each do |previous_land, land| %>
    <tr class="<%= land_use_class(land) %>">
      <td class="">
        <div class="region_short_name" title="<%= land.region.name %>">
          <%= show_region_link land.region %> - <%= link_to land.land_type, land_type_path(land.land_type.parameterize('_')) %>
        </div>
      </td>
      <td class="numeric">
        <%= number_with_precision(previous_land.hectares, :precision => 0, :delimiter => ',') if previous_land %>
      </td>
      <td class="numeric">
        <%= number_with_precision(land.hectares, :precision => 0, :delimiter => ',') if land %>
      </td>
      <td class="numeric">
        <%= number_with_precision(land.hectares - previous_land.hectares, :precision => 0, :delimiter => ',') if previous_land %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= javascript_tag do %>
  $('#land_type').change(function(){
    if(this.value == 'All') {
      $('tr.odd').removeClass('odd');
      $('#land_use').addClass('zebra-striped');
      $('tr:hidden').show();
    } else {
      $('#land_use').removeClass('zebra-striped');
      $('tr.odd').removeClass('odd');
      var selector = 'tbody tr.' + this.value.toLowerCase();
      $('tbody tr:visible').hide()
      $(selector).show();
      $('#land_use tbody tr:visible:even').addClass('odd')
    }
  });
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Land and Waste New Zealand</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'fips', 'd3/d3.min.js', 'd3/d3.geo.min.js', 'd3/d3.geom.min.js', 'protovis/protodata.js', 'polymaps.min.js' %>

  <%= yield :head %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="topbar">
      <div class="topbar-inner">
        <div class="container">
          <h3><%= link_to 'Land and Waste'.html_safe, root_path %></h3>
          <ul class="nav">
            <li class="dropdown">
              <%= link_to_function 'Regions', "$(this).parent().toggleClass('open')" %>
              <ul class="dropdown-menu">
                <% (@regions || Region.showable.all).each do |region| %>
                  <li><%= link_to region.name, region_path(region) %></li>
                <% end %>
              </ul>
            </li>
            <li class="<%= 'active' if current_page?(land_path) %>">
              <%= link_to 'Land', land_path %>
            </li>
            <li class="<%= 'active' if current_page?(waste_path) %>">
              <%= link_to 'Waste', waste_path %>
            </li>
          </ul>
          <ul class="nav secondary-nav">
            <li><%= link_to 'About', about_path(:anchor => 'about') %></li>
            <li><%= link_to 'Sources', about_path(:anchor => 'sources') %></li>
          </ul>
        </div>
      </div><!-- /topbar-inner -->
    </div>

  <div id="root_container" class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/regions/index.html.erb
<h2>Mapping New Zealand's Land and Waste</h2>

<p class="alert-message info">Please select a region to begin</p>

<% @regions.each do |region| %>
  <p><%= link_to region.name, region_path(region) %></p>
<% end %>

app/views/regions/show.html.erb
<h1><%= @region.name %></h1>

<dl>
<% unless @region.populations.empty? %>
  <dt>Population (<%= @region.populations.last.year %>)</dt>
  <dd><%= number_with_delimiter(@region.populations.last.number) %></dd>
<% end %>
  <dt>Land Area (km2)</dt>
  <dd><%= number_with_delimiter(@region.area.to_i) %></dd>
<% if @tonnage %>
  <dt><%= @tonnage.year %> landfill (tonnes):</dt>
  <dd><%= number_with_delimiter @tonnage.tonnes %></dd>
<% end %>
<% if @regional_council %>
  <dt>Regional council</dt>
  <dd><%= link_to @regional_council.name, @regional_council.website %></dd>
<% end %>
</dl>

<h2>Land</h2>

<p>
  <% if @forests.present? %>
    There were <%= number_with_delimiter @forests.last.hectares.round.to_i %> hectares of <%= @forests.last.land_type %> in <%= @region.name %> as of <%= @forests.last.year %>.
    <% if @forests.size > 1 %>
      <% difference = @forests.last.hectares - @forests.first.hectares %>
      This is <%= number_with_precision(difference.abs, :precision => 0, :delimiter => ',') %> hectares <%= difference < 0 ? 'less' : 'more' %> compared to <%= @forests.first.year %>.
    <% end %>
  <% end %>
</p>

<% if @lands.present? %>
  <p>The most common type of land in <%= @region.name %> are <strong><%= @lands.first.land_type.pluralize %></strong>.
  <%= link_to 'Compare with other regions &raquo;'.html_safe, land_path, :class => 'btn primary' %>
  </p>

  <div class="row">
    <table class="span8 column">
      <thead>
        <tr>
          <th>Land use type (<%= @lands.first.year %>)</th>
          <th class="numeric">Hectares</th>
          <th class="numeric">% of region</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <%= link_to_function @region.name, "scale(1); densityInfo(0)" %>
          </td>
          <td><%= @region.area %> km2</td>
          <td></td>
        <tr>
        <% @lands.each do |land| %>
          <tr>
            <td>
        <%= link_to_function land.land_type, "scale(#{number_with_precision(land.hectares / @region.area / 100, :precision => 5)}); densityInfo(#{land.id})" %>
</td>
            <td class="numeric"><%= number_with_precision(land.hectares, :delimiter => ',', :precision => 1) %></td>
            <td class="numeric"><%= number_to_percentage (land.hectares / @region.area), :precision => 1  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div id="map" style="height: 500px;" class="span8 column"></div>
  </div>

<% else %>
  <p class="alert-message warning">No land use data available</p>
<% end %>



<h2>Waste</h2>

<p>
  In <%= @tonnage.year %>, <%= 'an estimated' if @tonnage.estimate %>
  <code><%= number_to_human(@tonnage.tonnes).downcase %> tonnes</code> of waste was dumped in landfills in the region.
  <%= link_to 'Compare with other regions &raquo;'.html_safe, waste_path, :class => 'btn primary' %>
</p>

      <div class="density-info" id="density-0">
        <p>
        <%= @region.name %> had <code><%= number_with_precision(kg_per_meter(@tonnage.tonnes, @region.area), :precision => 1) %> kgs per meter of land</code> 
        in the year <%= @tonnage.year %>
        </p>
        <p>
        Alternatively, that's <%= number_with_precision(@tonnage.tonnes / @region.area, :delimiter => ',', :precision => 0) %> tonnes per 1 km<sup>2</sup> of <%= 'total region area' %>
        </p>
      </div>
      <% @lands.each do |land| %>
        <% density = kg_per_meter(@tonnage.tonnes, land.square_kms) %>
        <div class="density-info" id="density-<%=land.id%>" style="display:none">
          <p>
          <%= rubbish_phrase(density) %> the <%= land.land_type.pluralize %> of the region,
          we would find <code>a <%= number_with_precision(density, :precision => 1) %> kg block of rubbish every meter</code>.
          </p>
          <p>
          Alternatively, that's <%= number_with_precision(@tonnage.tonnes / land.hectares * 100, :delimiter => ',', :precision => 0) %> tonnes per 1 km<sup>2</sup> 
          </p>
        </div>
      <% end %>



<h2>Other sources</h2>
<% if @regional_council %>
  <p>
    Much, much more wonderful information and data can be found at the <%= link_to @region.name + ' Region wikipedia page', 'http://en.wikipedia.org/wiki/' + @region.name + ' Region' %>
  </p>
<% end %>


<%= javascript_tag do %>
  var tonnage = <%= raw @tonnage.to_polymaps_json %>;

  var tonnes = {}
  for (var t in tonnage) {
    tonnes[regc[t]] = tonnage[t];
  }
<% end %>
<%= javascript_include_tag 'density.js' %>